# Generated by Django 3.2.9 on 2022-04-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BootstrapQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bootstrap soraglar',
                'verbose_name_plural': 'Bootstrap Soraglar',
            },
        ),
        migrations.CreateModel(
            name='DjangoQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Django soraglar',
                'verbose_name_plural': 'Django Soraglar',
            },
        ),
        migrations.CreateModel(
            name='HtmlCssQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Html&Css soraglar',
                'verbose_name_plural': 'Html&Css Soraglar',
            },
        ),
        migrations.CreateModel(
            name='JavaScriptQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'JavaScript soraglar',
                'verbose_name_plural': 'JavaScript Soraglar',
            },
        ),
        migrations.CreateModel(
            name='NodejsQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nodejs soraglar',
                'verbose_name_plural': 'Nodejs Soraglar',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Python soraglar',
                'verbose_name_plural': 'Python Soraglar',
            },
        ),
    ]
