# Generated by Django 3.2.9 on 2022-05-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='name',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='email',
        ),
        migrations.AddField(
            model_name='messages',
            name='from_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
