# Generated by Django 3.2.9 on 2022-04-05 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.questions')),
            ],
            options={
                'verbose_name': 'Python Jogaplar',
                'verbose_name_plural': 'Python Jogaplar',
            },
        ),
        migrations.CreateModel(
            name='NodejsAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('nodejs_question', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.nodejsquestions')),
            ],
            options={
                'verbose_name': 'Nodejs Jogaplar',
                'verbose_name_plural': 'Nodejs Jogaplar',
            },
        ),
        migrations.CreateModel(
            name='JavaScriptAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('javascript_question', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.javascriptquestions')),
            ],
            options={
                'verbose_name': 'JavaScript Jogaplar',
                'verbose_name_plural': 'JavaScript Jogaplar',
            },
        ),
        migrations.CreateModel(
            name='HtmlCssAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('htmlcss_question', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.htmlcssquestions')),
            ],
            options={
                'verbose_name': 'Html&Css Jogaplar',
                'verbose_name_plural': 'Html&Css Jogaplar',
            },
        ),
        migrations.CreateModel(
            name='DjangoAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('django_question', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.djangoquestions')),
            ],
            options={
                'verbose_name': 'Django Jogaplar',
                'verbose_name_plural': 'Django Jogaplar',
            },
        ),
        migrations.CreateModel(
            name='BootstrapAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('bootstrap_question', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.bootstrapquestions')),
            ],
            options={
                'verbose_name': 'Bootstrap Jogaplar',
                'verbose_name_plural': 'Bootstrap Jogaplar',
            },
        ),
    ]
